version: '3.8'

services:
  app:
    image: 'fast-food-it-park:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fast_food
      - SPRING_DATASOURCE_USERNAME=learn
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=learn
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=fast_food
    ports:
      - "5433:5432"
